name: Deploy Azure Blob with Terraform.

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: "Azure Resource Group name"
        required: true
        default: "rg-demo"
      location:
        description: "Azure Region"
        required: true
        default: "East US"
      storage_account_name:
        description: "Storage Account name (must be unique)"
        required: true
        default: "adityastorageaccnt"
      container_name:
        description: "Blob Container name"
        required: true
        default: "mycontainer"
      port_context:
        required: true
        description: "Details about the action and general context (blueprint, run id, etc...)"
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Debug Azure Environment
        run: |
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"
          az account show

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/azure/blob

      - name: Terraform Apply
        run: |
         terraform apply -auto-approve \
          -var="resource_group_name=${{ github.event.inputs.resource_group_name }}" \
          -var="location=${{ github.event.inputs.location }}" \
          -var="storage_account_name=${{ github.event.inputs.storage_account_name }}" \
          -var="container_name=${{ github.event.inputs.container_name }}"
        working-directory: ./terraform/azure/blob

      - name: Notify Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          baseUrl: https://api.getport.io
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Instance Provisioned
          status: SUCCESS
