name: Deploy Azure Blob with Terraform

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: "Azure Resource Group name"
        required: true
        default: "rg-demo"
      location:
        description: "Azure Region"
        required: true
        default: "East US"
      storage_account_name:
        description: "Storage Account name (must be unique)"
        required: true
        default: "mystorageacct${{ github.run_number }}"
      container_name:
        description: "Blob Container name"
        required: true
        default: "mycontainer"
      port_context:
        required: true
        description: "Details about the action and general context (blueprint, run id, etc...)"
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/azure/blob

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="resource_group_name=${{ github.event.inputs.resource_group_name }}" \
          -var="location=${{ github.event.inputs.location }}" \
          -var="storage_account_name=${{ github.event.inputs.storage_account_name }}" \
          -var="container_name=${{ github.event.inputs.container_name }}"
        working-directory: ./terraform/azure/blob
